### ISSUE TITLE
New version stopped working

### ISSUE THREAD

**Issue by adhawkins** [KenKundert/borg-space#4]
When I try to use the new version, I'm getting an error:

```
xcp-alpine-test:~# emborg --version
1.27.0 (2021-09-21)
xcp-alpine-test:~# borg-space luned
Traceback (most recent call last):
  File "/usr/bin/borg-space", line 173, in <module>
    generate_report(
  File "/usr/bin/borg-space", line 108, in generate_report
    if emborg.version < (1,27) or configs is None:
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'
```

**Comment by adhawkins** [comment]
Looks like the 'version' API property was added after v1.27 was released, which is the last tagged version on GitHub.

**Comment by KenKundert** [comment]
Sorry about that. Please give it another try.

**Comment by adhawkins** [comment]
Looks good, thanks.
